### Numpy array with basics

In [1]:
import numpy as np

creating array from list

In [4]:
arr_1D = np.array([1, 2, 3])
arr_2D = np.array([[4, 5, 6], 
                   [7, 8, 9]])

print("1D Array:", arr_1D)
print("\n2D Array:", arr_2D)


1D Array: [1 2 3]

2D Array: [[4 5 6]
 [7 8 9]]


## List vs Numpy array

In [ ]:
py_list = [1, 2, 3]
print("Python List Multiplication:", py_list*2)

np_array = np.array([1, 2, 3])
print("NumPy Array Multiplication:", np_array*2) # element wise multiplication

Python List Multiplication: [1, 2, 3, 1, 2, 3]


## Creating array with strach

In [ ]:
zeros = np.zeros((3, 3))
print("Array of zeros:\n", zeros)

ones = np.ones((3, 3))
print("Array of ones:\n", ones)

full = np.full((3, 3), 7) # Create a 3x3 array filled with the value 7
print("Array filled with 7:\n", full)

random = np.random.randint(0, 10, (3, 3)) # Create a 3x3 array with random values between 0 and 10
print("Array of random values:\n", random)

sequence = np.arange(0, 10, 2) # Create an array with values from 0 to 10 with a step of 2
print("Array with a sequence of numbers:\n", sequence)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Array of random values:
 [[6 7 6]
 [3 8 0]
 [9 1 3]]
